# Generated by Django 3.2.9 on 2021-12-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='attributes',
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
