# Generated by Django 3.2.9 on 2021-12-30 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20211230_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='details',
        ),
    ]
